base_bledvoyage:
    resource: "@BaseBledvoyageBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: |fr|en|es

base_user:
    resource: "@BaseUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/
    requirements:
        _locale: |fr|en|es
