security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MODERATEUR, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        custom:
            id: s4a_user.my_provider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: custom  #fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    
    #access_decision_manager:
        #strategy: unanimous
    
    access_control:
        - { path: ^/login$,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/product$,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/type$,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /manager,         role: [ROLE_ADMIN, ROLE_MODERATEUR] }
        - { path: /_console/,       role: ROLE_ADMIN }
        - { path: ^/booking,        role: ROLE_USER }
        - { path: ^/avis$,          role: ROLE_USER }
        - { path: ^/suggest,        role: ROLE_USER }
        - { path: /promotion/.*,    role: ROLE_USER }
