Base\BledvoyageBundle\Entity\Categorie:
    type: entity
    table: null
    repositoryClass: Base\BledvoyageBundle\Entity\CategorieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        image:
            type: string
            length: 255
        afficher:
            type: string
            length: 255
        ip:
            type: string
            length: 255
        dateTime:
            type: datetime
            column: date_time
    lifecycleCallbacks: {  }
