base_bledvoyage_homepage:
    path:     /
    defaults: { _controller: BaseBledvoyageBundle:Default:index }

index:
    path:     mail
    defaults: { _controller: BaseBledvoyageBundle:Mail:index }

sortie_nroho:
    type:     rest
    resource: Base\BledvoyageBundle\Controller\NrohoController
    prefix:   api

bledvoyage_product:
    path:     /{id}/{slug}
    defaults: { _controller: BaseBledvoyageBundle:Default:product }
    requirements:
        id:   \d+

bledvoyage_booking:
    path:     /booking/{id}
    defaults: { _controller: BaseBledvoyageBundle:Default:booking }
    requirements:
        id:   \d+

bledvoyage_promotion:
    path:     /promotion
    defaults: { _controller: BaseBledvoyageBundle:Default:promotion }

bledvoyage_promotion_type:
    path:     /promotion/{id}
    defaults: { _controller: BaseBledvoyageBundle:Default:promotionType }
    requirements:
        id:   \d+

bledvoyage_type:
    path:     /type/{id}
    defaults: { _controller: BaseBledvoyageBundle:Default:type }
    requirements:
        id:   \d+

bledvoyage_avis:
    path:     /avis/{id}
    defaults: { _controller: BaseBledvoyageBundle:Default:avis }
    requirements:
        id:   \d+

bledvoyage_suggest:
    path:     /suggest
    defaults: { _controller: BaseBledvoyageBundle:Default:suggest }
    
bledvoyage_contact:
    path:     /contact
    defaults: { _controller: BaseBledvoyageBundle:Default:contact }

bledvoyage_teambuilding:
    path:     /teambuilding
    defaults: { _controller: BaseBledvoyageBundle:Default:teambuilding }

bledvoyage_teambuilding_pdf:
    path:     /teambuilding/offre_journée_team_building.pdf
    defaults: { _controller: BaseBledvoyageBundle:Default:pdfTeambuilding }

bledvoyage_admin:
    path:     manager
    defaults: { _controller: BaseBledvoyageBundle:MurAdmin:index }

bledvoyage_admin_del_statut:
    path:     manager/del/{id}
    defaults: { _controller: BaseBledvoyageBundle:MurAdmin:delStatut }
    requirements:
        id:   \d+
    
bledvoyage_admin_reservation:
    path:     manager/reservation
    defaults: { _controller: BaseBledvoyageBundle:Admin:reservation }

bledvoyage_admin_commande:
    path:     manager/commande
    defaults: { _controller: BaseBledvoyageBundle:Admin:commande }

bledvoyage_admin_listes:
    path:     manager/listes
    defaults: { _controller: BaseBledvoyageBundle:Admin:listes }

bledvoyage_admin_present:
    path:     manager/present
    defaults: { _controller: BaseBledvoyageBundle:Admin:present }

bledvoyage_admin_commande_note:
    path:     manager/commande/note/{id}
    defaults: { _controller: BaseBledvoyageBundle:Admin:commandeNote }
    requirements:
        id:   \d+

bledvoyage_admin_commande_facturer:
    path:     manager/commande/facturer/{id}
    defaults: { _controller: BaseBledvoyageBundle:Admin:commandeFacturer }
    requirements:
        id:   \d+

bledvoyage_admin_commande_confirmer:
    path:     manager/commande/confirmer/{id}
    defaults: { _controller: BaseBledvoyageBundle:Admin:commandeConfirmer }
    requirements:
        id:   \d+

bledvoyage_admin_reservation_note:
    path:     manager/reservation/note/{id}
    defaults: { _controller: BaseBledvoyageBundle:Admin:reservationNote }
    requirements:
        id:   \d+

bledvoyage_admin_reservation_avis:
    path:     manager/reservation/avis/{id}
    defaults: { _controller: BaseBledvoyageBundle:Admin:reservationAvis }
    requirements:
        id:   \d+

bledvoyage_admin_reservation_confirmer:
    path:     manager/reservation/confirmer/{id}
    defaults: { _controller: BaseBledvoyageBundle:Admin:reservationConfirmer }
    requirements:
        id:   \d+

bledvoyage_admin_reservation_acompte:
    path:     manager/reservation/acompte/{id}
    defaults: { _controller: BaseBledvoyageBundle:Admin:reservationAcompte }
    requirements:
        id:   \d+

bledvoyage_admin_statisqtique:
    path:     manager/statistic
    defaults: { _controller: BaseBledvoyageBundle:Admin:statisticMois }

bledvoyage_admin_stat_year:
    path:     manager/statistic/{year}
    defaults: { _controller: BaseBledvoyageBundle:Admin:statisticMois }
    requirements:
        year: \d+

bledvoyage_admin_invitation:
    path:     manager/invitation
    defaults: { _controller: BaseBledvoyageBundle:Admin:invitation }

bledvoyage_admin_devis_entreprise:
    path:     manager/devis
    defaults: { _controller: BaseBledvoyageBundle:Admin:devisEntreprise }
