base_bledvoyage_homepage:
    path:     /
    defaults: { _controller: BaseBledvoyageBundle:Default:index }

index:
    path:     Mail
    defaults: { _controller: BaseBledvoyageBundle:Mail:index }

sortie_nroho:
    type: rest
    resource: Base\BledvoyageBundle\Controller\NrohoController
    prefix: api

bledvoyage_product:
    path:     /product/{id}
    defaults: { _controller: BaseBledvoyageBundle:Default:product }
    requirements:
        id:   \d+

bledvoyage_booking:
    path:     /booking/{id}
    defaults: { _controller: BaseBledvoyageBundle:Default:booking }
    requirements:
        id:   \d+

bledvoyage_admin:
    path:     manager
    defaults: { _controller: BaseBledvoyageBundle:Admin:index }

bledvoyage_admin_commande:
    path:     manager/commande
    defaults: { _controller: BaseBledvoyageBundle:Admin:commande }

bledvoyage_admin_reservation:
    path:     manager/reservation
    defaults: { _controller: BaseBledvoyageBundle:Admin:reservation }

bledvoyage_admin_present:
    path:     manager/present
    defaults: { _controller: BaseBledvoyageBundle:Admin:present }
