base_bledvoyage_homepage:
    path:     /
    defaults: { _controller: BaseBledvoyageBundle:Default:index }

index:
    path:     Mail
    defaults: { _controller: BaseBledvoyageBundle:Mail:index }

sortie_nroho:
    type: rest
    resource: Base\BledvoyageBundle\Controller\NrohoController
    prefix: api

bledvoyage_product:
    path:     /product/{id}
    defaults: { _controller: BaseBledvoyageBundle:Default:product }
    requirements:
        id:   \d+

bledvoyage_booking:
    path:     /booking/{id}
    defaults: { _controller: BaseBledvoyageBundle:Default:booking }
    requirements:
        id:   \d+
