parameters:
#    base_bledvoyage.example.class: Base\BledvoyageBundle\Example

services:
#    base_bledvoyage.example:
#        class: %base_bledvoyage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
