parameters:
    #base_bledvoyage.example.class: Base\BledvoyageBundle\Example

services:
    FrToDatetime:
        class: Base\BledvoyageBundle\Service\DateFunction\FrToDatetime

    dateFromNumberWeek:
        class: Base\BledvoyageBundle\Service\DateFunction\DateFromNumberWeek
